cpu_threshold: 85
memory_threshold: 90
interval_seconds: 30

services:
  - Spooler
  - W32Time

endpoints:
  - name: Google
    url: https://www.google.com
    timeout: 2
  - name: Dummy API
    url: https://dummy-api.local/health
    timeout: 2